spring.application.name=franchiseapi
spring.r2dbc.url=r2dbc:mysql://mysql:3306/franchise_db
spring.r2dbc.username=franchise_user
spring.r2dbc.password=franchise_pass
server.port=8080
security.jwt.secret=c3VwZXItc2VjdXJlLXN1cGVyLWxvbmctc2VjcmV0LWtleS0xMjM0NTY3ODkw
security.jwt.expiration=86400000
springdoc.swagger-ui.path=/swagger-ui.html